# Generated by Django 5.1.7 on 2025-04-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id_celda', models.AutoField(primary_key=True, serialize=False)),
                ('numero_celda', models.CharField(max_length=10)),
                ('capacidad_maxima', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detenido',
            fields=[
                ('id_detenido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('historial', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'detenido',
                'ordering': ['id_detenido'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Guardiaseguridad',
            fields=[
                ('id_guardia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'guardia_seguridad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permiso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personalmedico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personalmedico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id_visitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('relacion_con_detenido', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'visitante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('id_detenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.detenido')),
                ('id_guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.guardiaseguridad')),
            ],
            options={
                'db_table': 'incidente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ocupacioncelda',
            fields=[
                ('id_ocupacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('id_celda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.celda')),
                ('id_detenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.detenido')),
            ],
            options={
                'db_table': 'ocupacion_celda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Atencionmedica',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('id_detenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.detenido')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.personalmedico')),
            ],
            options={
                'db_table': 'atencion_medica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rolpermiso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.permiso')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id_traslado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_traslado', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('id_celda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celda_destino', to='src.celda')),
                ('id_celda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celda_origen', to='src.celda')),
                ('id_detenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.detenido')),
                ('id_guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.guardiaseguridad')),
            ],
            options={
                'db_table': 'traslado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.rol')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('id_registro_afectado', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('detalles', models.JSONField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.usuario')),
            ],
            options={
                'db_table': 'auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateTimeField()),
                ('tipo_visita', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=False)),
                ('id_detenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.detenido')),
                ('id_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.visitante')),
            ],
            options={
                'db_table': 'visita',
                'managed': True,
            },
        ),
    ]
